DROP TABLE IF EXISTS documents;
CREATE TABLE IF NOT EXISTS documents (id INTEGER PRIMARY KEY, text TEXT NOT NULL);
DROP TABLE IF EXISTS images;
CREATE TABLE IF NOT EXISTS images (id INTEGER PRIMARY KEY, description TEXT NOT NULL url TEXT NOT NULL);