name = "masters-bot"
main = "src/index.js"
compatibility_date = "2024-12-30"

# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases
[[d1_databases]]
binding = "DOC_DB"
database_name = "document-store"
database_id = "f23758c2-d6ba-47b9-a347-140e68491a7d"

# Static assets configuration
[site]
bucket = "./public"

# Bind a dispatch namespace. Use Workers for Platforms to deploy serverless functions programmatically on behalf of your customers.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#dispatch-namespace-bindings-workers-for-platforms
# [[dispatch_namespaces]]
# binding = "MY_DISPATCHER"
# namespace = "my-namespace"

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#durable-objects

# Bind a Vectorize index. Use to store and query vector embeddings for semantic search, classification and other vector search use-cases.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#vectorize-indexes
[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "vector-index"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[ai]
binding = "AI"
